# Author: Sylvia Amihere @ SMU

#target : dependencies
driver.exe : driver.cpp one_norm.cpp vector_difference.cpp vector_product.cpp vector_sum.cpp
	g++ -o driver.exe driver.cpp one_norm.cpp vector_difference.cpp vector_product.cpp vector_sum.cpp

clean :
	rm -f *.o
